# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10

In [3]:
print(np.zeros(10, dtype=int))

[0 0 0 0 0 0 0 0 0 0]


#### 4.  How to find the memory size of any array

In [4]:
arr = np.ones(10, dtype=int)
print('size of arr {} is {} bytes'.format(arr,np.prod((arr.size,arr.itemsize))))

size of arr [1 1 1 1 1 1 1 1 1 1] is 40 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [5]:
n = np.zeros(10, dtype=int)
n[4] = 1
print(n)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49

In [7]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [8]:
print(arr[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
arr = (np.arange(9)).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### 11. Create a 3x3 identity matrix

#### 12. Create a 3x3x3 array with random values

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

#### 14. Create a random vector of size 30 and find the mean value

#### 15. Create a 2d array with 1 on the border and 0 inside

#### 16. How to add a border (filled with 0's) around an existing array?

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?